[package]
name = "limine-rust-template"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.21", default-features = false, features = ["derive"] }
flantermbindings = "0.1.3"
limine = "0.5"
